targets:
  $default:
    sources:
      exclude:
        - core_package/*
    builders:
      json_serializable:
        options:
          any_map: true
          checked: false
          create_to_json: false
          disallow_unrecognized_keys: false
          explicit_to_json: true
          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: false
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - prefer_const_declarations
