arb-dir: assets/l10n
template-arb-file: app_ar.arb
output-localization-file: translations.dart
output-dir: ./lib/generated/translation
output-class: Translations
untranslated-messages-file: desiredFileName.txt

